---
- name: "Restart nginx"
  service: name=nginx state=restarted
  become: true

- name: "Restart PHP"
  service: name=php7.4-fpm state=restarted
  become: true

- name: "Restart MariaDB"
  service: name=mariadb-server state=restarted
  become: true
