---
- name: "Update apt cache (forced)"
  become: true
  package: update_cache=yes state=latest cache_valid_time=0

- name: "Update system"
  become: true
  package: update_cache=yes state=latest cache_valid_time=86400
  when: ansible_os_family == 'Debian'
