---
- name: "Create Kafka directory"
  file:
    path: /opt/kafka
    state: directory

- name: "Copy compose file to host"
  template:
    src: docker_compose.yml.j2
    dest: /opt/kafka/docker-compose.yml
    owner: root
    group: root
    mode: 0644

- name: "Compose the Kafka stack"
  community.docker.docker_compose:
    project_src: /opt/kafka
    project_name: kafka
    restarted: yes
    recreate: smart
